## 7. [드림코딩 JS - 7. Callback, Promise, async & await]
자바스크립트sms 동기적이어서 코드가 순차적으로 실행되며 비동기 처리를 위한 `Callback`, `Promise`, `await/async`가 있다.   
비동기 처리를 하는 간단한 이유는 원하는 때에 동작이 시작할 수 있도록 하기 위함이 있다.

### Callback
```js
console.log('1');
setTimeout(() => console.log('2'), 1000);
console.log('3');

// 1
// 3
// 2 (setTimeout() 호출 후 1초 뒤에)
```
- 위 코드에서 setTime() 메서드의 매개변수인 consloe.log()는 바로 실행되는 것이 아니라 1초 뒤애 실행하는 콜백함수이다.

#### Synchronous callback
```js
// 즉각적으로 실행되는 콜백 함수
function printImmediately(print) {
    print();
}

printImmediately(() => console.log('hello'));   // hello
```

#### Asynchronous callback
```js
// 언제 실행되는지 예측할 수 없는 콜백 함수
function printWithDelay(print, timeout) {
    setTimeout(print, timeout);
}

printWithDelay(() => console.log('async callback'), 2000);  // async callback (2초 후 실행)
```
#### Callback Hell
```js
class UserStorage {
    loginUser(id, password, onSuccess, onError) {
        setTimeout(() => {
            if (
                (id === 'raccoon' && password === '123') ||
                (id === 'cat' && password === '456')
            ) {
                onSuccess(id);
            } else {
                onError(new Error('not found'));
            }
        }, 2000);
    }

    getRoles(user, onSuccess, onError) {
        setTimeout(() => {
            if (user === 'raccoon') {
                onSuccess({ name: 'raccoon', role: 'admin'});
            } else {
                onError(new Error('no access'));
            }
        }, 1000);
    }
}

const userStorage = new UserStorage();
const id = prompt('enter your id');
const password = prompt('enter your password');
userStorage.loginUser(
    id,
    password,
    user => {
        userStorage.getRoles(
            user, 
            userWithRole => {
                alert(`hello, ${userWithRole.name}, you have a ${userWithRole.role} role`);
            },
            error => {
                console.log(error);
            }
        );
    },
    error => {
        console.log(error);
    }
);
```
- 사용자에게 id, password를 입력 받아 가입된 사용자인지, 권한이 있는지 확인하는 코드로 setTimeout()을 이용해 시간차를 둬서 서버와 통신한다고 가정한다.  
- 위 코드처럼 꼬리를 무는 비동기 동작이 많아지면 가독성이 떨어지며 깊은 중첩 코드로 인한 `콜백 지옥 패턴`을 맞이하게 된다.

***  

### Promise
```js
let promise = new Promise(function(resolve, reject) {
  // executor (제작 코드, '가수')
});
```
- 콜백 함수 대신 유용하게 사용할 수 있는 비동기 처리를 위한 `JavaScript 객체`다.
- new Promise 생성자가 반환하는 promise 객체는 `state`, `result` 라는 내부 프로퍼티를 갖는다.
- `state`, `result` 내부 프로퍼티는 개발자가 직접 접근할 수 없으며  `.then`/ `.catch`/ `.finally` 메서드로 접근 가능하다.
- promise에서 중요한 포인트는 state, producer & consuemr 이다.
- `state` - operation을 수행 중인지, 수행 완료 했는지, 수행 실패했는지에 대한 상태
  - `pending` - promise가 만들어져서 우리가 지정한 operation이 수행 중일 경우
  - `fulfilled` - operation이 성공적으로 수행된 경우
  - `rejected` - operation이 실패한 경우
- `result` - 처음엔 undefined, resolve(value)가 호출되면 `value`, reject(error)가 호출되면 `error`로 변한다.
- `producer & consumer` - 간단하게 데이터를 제공하는 사람, 제공된 데이터를 사용하는 사람의 차이

#### Producer
- Promise 객체를 만드는 순간 내부의 `executor`라는  함수가 바로 실행된다.
- 따라서 버튼 클릭시 처리해야 하는 일인 경우 promise 객체를 생성하면 불필요한 네트워크 통신이 이뤄질 수 있다.
```js
const promise = new Promise((resolve, reject) => {
    // doing some heavy work (network, read files..)
    console.log('doing something...');
    setTimeout(() => {
        // resolve('raccoon');  // (operation에 성공했을 경우) raccoon
        reject(new Error('no network'));    // (operation에 실패했을 경우) Uncaught (in promise) Error: no network
    }, 2000);
});
```

#### Consumer
- Promise 객체는 executor 실행 함수와 결과나 에러를 받을 소비 함수를 이어주는 역할을 한다.
- 소비 함수는 `then()`, `catch()`, `finally()` 메서드를 사용한다.
```js
promise
    .then((value) => {
        console.log(value); // raccoon
    })
    .catch(error => {
        console.log(error); // Error: no network
    })
    .finally(() => {    // 성공 실패 여부와 상관없이 무조건 실행하고 싶을 경우
        console.log('finally'); // finally
    });
// then 호출시 Promise 객체가 return 되기에 그 객체에 catch를 적용함 (체이닝)
```

#### Consumer - then()
```js
promise.then(
  function(result) { /* 결과(result)를 다룹니다 */ },
  function(error) { /* 에러(error)를 다룹니다 */ }
);
```
- 첫번째 인수는 promise가 `이행`되었을 때 실행하는 함수로 여기서 `실행 결과`를 받는다.
- 두번째 인수는 promise가 `거부`되었을 때 실행되는 함수고, 여기서 `에러`를 받는다.
- 작업이 성공적으로 처리된 경우만 다루고 싶다면 then()에 인수를 하나만 전달한다.

### Promise chaining
- 비동기 작업이 여러 개 있을 경우 `Promise chaining`을 이용할 수 있다.
```js
const fetchNumber = new Promise((resolve, reject) => {
    setTimeout(() => resolve(1), 1000);
});

fetchNumber
    .then(num => num * 2)
    .then(num => num * 3)
    .then(num => {
        return new Promise((resolve, reject) => {
            setTimeout(() => resolve(num - 1), 1000);
        });
    })
    .then(num => console.log(num)); // 5
```
- promise chaining이 가능한 이유는 fetchNumber 는 promise 객체고 promise.then()을 하면 promise가 반환되기 때문이다. 거기에는 당연히 then()을 호출할 수 있다.  
**Q) then()은 promise에만 사용할 수 있는 메서드 아닌가?**    
→ 핸들러가 값을 반환하면 `result`가 되고 다음 then()은 이 값을 이용해 호출된다. 

### Promise Error Handling
- promise가 거부되면 제어 흐름이 제일 가까운 rejection 핸들러로 넘어가기에 `promise chaining`을 사용하여 에러를 쉽게 처리할 수 있다.
- 아래 에러 발생시 코드처럼 `catch()`는 첫번째 핸들러일 필요가 없으며 여러 개의 `then()` 뒤에 올 수도 있다.
```js
// 정상 코드
const getHen = () =>
    new Promise((resolve, reject) => {
        setTimeout(() => resolve('🐓'), 1000);
    });
const getEgg = hen =>
    new Promise((resolve, reject) => {
        setTimeout(() => resolve(`${hen} => 🥚`), 1000);
    });
const cook = egg =>
    new Promise((resolve, reject) => {
        setTimeout(() => resolve(`${egg} => 🍳`), 1000);
    });

getHen()
    .then(getEgg)   // 콜백함수 전달시 받아오는 value를 다른 함수에 바로 넣어주는 경우 value 생략 가능
    .then(egg => cook(egg))
    .then(meal => console.log(meal))   // 🐓 => 🥚 => 🍳
    .catch(console.log);
```
```js
// 에러가 생겼을 경우
const getHen = () =>
    new Promise((resolve, reject) => {
        setTimeout(() => resolve('🐓'), 1000);
    });
const getEgg = hen =>
    new Promise((resolve, reject) => {
        setTimeout(() => reject(new Error(`${hen} => 🥚`)), 1000);   // 에러 발생 !!! 
    });
const cook = egg =>
    new Promise((resolve, reject) => {
        setTimeout(() => resolve(`${egg} => 🍳`), 1000);
    });

getHen()
    .then(getEgg)   // 콜백함수 전달시 받아오는 value를 다른 함수에 바로 넣어주는 경우 value 생략 가능
    .catch(error => {   // 계란을 받아오는 것에 문제가 생길 경우 빵으로 대체하는 코드
        return '🍞';
    })
    .then(egg => cook(egg))
    .then(meal => console.log(meal))   // 🍞 => 🍳
    .catch(console.log);
```

#### 만약 catch()가 없다면 ?
```js
new Promise(function() {
  noSuchFunction(); // 에러 (존재하지 않는 함수)
})
  .then(() => {
    // 성공상태의 프라미스를 처리하는 핸들러. 한 개 혹은 여러 개가 있을 수 있음
  }); // 끝에 .catch가 없음!
```
- 에러 발생시 promise는 거부 상태가 되고, 예외 처리를 해줄 핸들러가 없기에 에러가 '갇혀버린다'.
- 자바스크립트 엔진은 promise 거부를 추적하다 위와 같은 상황 발생시, 전역 에러를 생성하며 브라우저 환경에선 `unhandledrejection` 이벤트로 잡을 수 있다.
```js
window.addEventListener('unhandledrejection', function(event) {
  // 이벤트엔 두 개의 특별 프로퍼티가 있습니다.
  alert(event.promise); // [object Promise] - 에러를 생성하는 프라미스
  alert(event.reason); // Error: 에러 발생! - 처리하지 못한 에러 객체
});

new Promise(function() {
  throw new Error("에러 발생!");
}); // 에러 처리 핸들러, catch가 없음
```
- `unhandledrejection` 핸들러는 에러 정보가 담긴 `event` 객체를 받기에 이 핸들러 안에서 원하는 작업을 할 수 있다.
- 대개 이런 에러는 회복할 수 없기에 개발자로서 할 수 있는 최선의 방법은 사용자에게 문제 상황을 알리고 가능하면 서버에 에러 정보를 보내는 것이다.
    
### Callback hell to Promise 정답 코드 
<details markdown="1">  
<summary>해답</summary>   

```js
'use strict';
class UserStorage {
    loginUser(id, password) {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                if (
                    (id === 'raccoon' && password === '123') ||
                    (id === 'cat' && password === '456')
                ) {
                    resolve(id);
                } else {
                    reject(new Error('not found'));
                }
            })
        }, 2000);
    }

    getRoles(user) {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                if (user === 'raccoon') {
                    resolve({ name: 'raccoon', role: 'admin'});
                } else {
                    reject(new Error('no access'));
                }
            }, 2000);
        })
    }
}

const userStorage = new UserStorage();
const id = prompt('enter your id');
const password = prompt('enter your password');
userStorage
    .loginUser(id, password)
    .then(userStorage.getRoles)
    .then(console.log)
    .catch(console.log);
```

</details>   

***  

### Promise API
### Promise.all()
- 여러 개의 promise를 `동시에 실행`시키고 모든 promise가 준비될 때까지 기다린 후 새로운 promise를 반환한다.
- 복수의 URL에 동시에 요청을 보내고, 다운로드가 모두 완료된 후 콘텐츠를 처리하는 경우 Promise.all을 사용할 수 있다.
- `Promise.all`에 전달되는 promise 중 하나라도 거부되면, Promise.all이 반환하는 promise는 에러와 함께 거부된다.
```js
Promise.all([
  new Promise(resolve => setTimeout(() => resolve(1), 3000)), // 1
  new Promise(resolve => setTimeout(() => resolve(2), 2000)), // 2
  new Promise(resolve => setTimeout(() => resolve(3), 1000))  // 3
]).then(alert); // 프라미스 전체가 처리되면 1, 2, 3이 반환됩니다. 각 프라미스는 배열을 구성하는 요소가 됩니다.
```
- 배열 안 promise가 처리되면 promise들의 결과값을 담은 배열이 새로운 promise의 `result`가 되며 위 코드의 result는 배열 `[1, 2, 3]`이 된다.
- 참고로 `Promise.all`의 첫 번째 promise는 가장 늦게 이행되더라고 처리 결과는 배열의 첫 번째 요소에 저장된다.

### Promise.race()
- `가장 먼저 처리`되는 promise의 결과(혹은 에러)를 반환한다.
```js
Promise.race([
  new Promise((resolve, reject) => setTimeout(() => resolve(1), 1000)),
  new Promise((resolve, reject) => setTimeout(() => reject(new Error("에러 발생!")), 2000)),
  new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000))
]).then(alert); // 1
```
- 첫 번째 promise가 가장 빨리 처리상태가 되기에 `1`이 `result` 값이 된다.
- `Promise.race`를 사용하면 '경주(race)의 승자'가 나타난 순간 다른 promise의 결과 또는 에러는 무시된다.

***  

### async & await
- ES8에서는 promise를 기반으로 동작하는 async & await가 도입되었다.

### async
- function 앞에 위치하며 `asyn`c 키워드 사용시 해당 함수는 항상 `promise`를 반환하고 promise가 아닌 값을 반환해도 fulfilled된 promise가 반환되도록 한다.
```js
async function fetchUser() {
    // do network request in 10 secs...
    return 'raccoon';
}

const user = fetchUser();
user.then(console.log); // raccoon

console.log(user); 
// Promise {<fulfilled>: 'raccoon'}
// [[Prototype]]: Promise
// [[PromiseState]]: "fulfilled"
// [[PromiseResult]]: "raccoon"
```

### await
- `async` 함수 안에서만 동작하여 JavaScript는 `await` 키워드를 만나면 promise가 처리(settled)될 때까지 기다렸다가 결과는 그 이후 반환된다.
- promise가 처리되기를 기다리는 동안 엔진이 다른 일(다른 스크립트 실행, 이벤트 처리 등)을 할 수 있기에. CPU 리소스가 낭비되지 않는다.
- 즉, `promise.then`보다 더 세련되게 promise의 `result` 값을 얻을 수 있게 해주는 문법이다.
```js
async function f() {

  let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("완료!"), 1000)
  });

  let result = await promise; // 프라미스가 이행될 때까지 기다림 (*)

  alert(result); // "완료!"
}

f();
```
- 위 코드에서 함수가 실행되는 도중에 `(*)`로 표시한 줄에서 실행이 중단되었다가 promise가 처리되면 실행이 재개된다.
- 이때 promise 객체의 result 값이 변수 result에 할당되며 위 예시를 실행하면 1초 뒤에 '완료!'가 출력된다.

- 또한 최상위 레벨 코드(top-level code)에선 `await`을 사용할 수 없다. 이럴 떈 익명 async 함수로 코드를 감싸면 최상위 레벨 코드에서도 사용할 수 있다.
```js
// 최상위 레벨 코드에선 문법 에러가 발생함
let response = await fetch('/article/promise-chaining/user.json');
let user = await response.json();

// 최상위 레벨 코드에서 await 사용 가능함
(async () => {
  let response = await fetch('/article/promise-chaining/user.json');
  let user = await response.json();
  ...
})();
```

#### async & await 예제 1
```js
function delay(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

async function getApple() {
    await delay(1000);
    return '🍎';
}

async function getBanana() {
    await delay(1000);
    return '🍌';
}

async function pickFruits() {
   const apple = await getApple();
   const banana  = await getBanana();
   return `${apple} + ${banana}`;
}

pickFruits().then(console.log); // 🍎 + 🍌
```
- 사과를 받아오고 바나나를 받아와서 모든 과일을 호출하는 예제
- 이런 상황에서 만약 getApple이 실행되는 동안 getBanana()가 기다릴 필요가 없다면 (두개의 함수가 연관 관계가 없다면) `Promise.all()`을 쓰는 것이 좋다.


#### async & await 예제 2
- async가 아닌 함수에서 async 함수 호출하기 퀴즈
- ‘일반’ 함수가 하나 있는데, 여기서 async 함수를 어떻게 하면 호출하고, 그 결과를 사용할 수 있을까?
```js
async function wait() {
  await new Promise(resolve => setTimeout(resolve, 1000));

  return 10;
}

function f() {
  // ...코드...
  // async wait()를 호출하고 그 결과인 10을 얻을 때까지 기다리려면 어떻게 해야 할까요?
  // f는 일반 함수이기 때문에 여기선 'await'를 사용할 수 없다는 점에 주의하세요!
}
```

<details markdown="1">  
<summary>해답</summary>   

```js
async function wait() {
  await new Promise(resolve => setTimeout(resolve, 1000));

  return 10;
}

function f() {
  // shows 10 after 1 second
  wait().then(result => alert(result));
}

f();
```
- `async` 함수를 호출하면 promise가 반환되므로 `.then`을 붙이면 된다.

</details>   

### async & await 에러 핸들링
- `try & catch`문이나 async함수에 `.catch`를 추가해 거부된 promise를 처리할 수 있다.
 ```js
 // 1. try & catch
async function f() {

  try {
    let response = await fetch('http://유효하지-않은-url');
    let user = await response.json();
  } catch(err) {
    // fetch와 response.json에서 발행한 에러 모두를 여기서 잡습니다.
    alert(err);
  }
}

f();

// 2. .catch
async function f() {
  let response = await fetch('http://유효하지-않은-url');
}

// f()는 거부 상태의 프라미스가 됩니다.
f().catch(alert); // TypeError: failed to fetch // (*)
```

### Callback to async & await 정답 코드
<details markdown="1">  
<summary>해답</summary>   

```js
'use strict';
// Callback Hell example
class UserStorage {
    loginUser(id, password) {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                if (
                    (id === 'raccoon' && password === '123') ||
                    (id === 'cat' && password === '456')
                ) {
                    resolve(id);
                } else {
                    reject(new Error('not found'));
                }
            })
        }, 2000);
    }

    getRoles(user) {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                if (user === 'raccoon') {
                    resolve({ name: 'raccoon', role: 'admin'});
                } else {
                    reject(new Error('no access'));
                }
            }, 2000);
        })
    }

    async getUserData(id, password) {
        try{
            const userId = await this.loginUser(id, password);
            const user = await this.getRoles(userId);
            alert(`hello, ${user.name}. you have ${user.role} role`);
        }catch (error) {
            console.log(error);
        }
    }
}


const userStorage = new UserStorage();
const id = prompt('enter your id');
const password = prompt('enter your password');
userStorage
    .getUserData(id, password);
```

</details> 

### 참고 자료(Reference)
[드림코딩 유튜브](https://www.youtube.com/watch?v=aoQSOZfz3vQ&list=PLv2d7VI9OotTVOL4QmPfvJWPJvkmv6h-2&index=13)   
[모던 자바스크립트 요약](https://ko.javascript.info/async-await)
